### ISSUE TITLE
用typora进行项目编号好粘贴到MDX Editor中显示的问题

### ISSUE THREAD

**Issue by Runnerxr** [maqi1520/mdx-editor#51]
![mmexport1709442923458.png](https://github.com/maqi1520/mdx-editor/assets/54966819/e840c6fa-e840-4efa-98ae-ece90c592534)

**Comment by maqi1520** [comment]
![image](https://github.com/maqi1520/mdx-editor/assets/9312044/f343fe84-5a2d-4c81-87a6-3878b3ee6406)

这是皮肤样式引起的，我会在未来修复，可以切换皮肤，或者覆盖 css 样式

```css
.markdown-body ol{
    list-style-type:decimal;
}
```
