### ISSUE TITLE
如何让自己的自定义样式生效？

### ISSUE THREAD

**Issue by zjh1943** [maqi1520/mdx-editor#68]
你好，非常感谢你们提供可以自定义样式的微信公众号编辑器，这大大提高了我写文章的效率！  
**但为什么我更改了自定义样式，却不生效呢？**  

我是 MacBook Pro 2022 款，我下载了 MDX Editor 编辑器本地版，我选择的 theme 为 Default。  
当我打开 `mdx-editor/plugins/thems/custom.css` 文件，改写 `h1` 的样式为如下所示。但在预览中，并没有看到样式变化。

```css
.markdown-body h1 {
  font-size: 16px;
  font-family: PingFangSC-light;
  color: rgb(31, 64, 230);
  border-bottom: 5px solid rgb(31, 64, 230);
}
```
如果我在你们的在线编辑器上更改 css 样式，则是能生效的。

请问我还要做一些额外的设置才能让我自定义的 css 样式生效吗？
